apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: food-order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName is omitted — cluster default will be used

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-order
  labels:
    app: food-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-order
  template:
    metadata:
      labels:
        app: food-order
    spec:
      containers:
        - name: food-order
          image: mandarveeam/food:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: "/app/data/order.db"
          volumeMounts:
            - name: db-storage
              mountPath: /app/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: food-order-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: food-order-service
spec:
  selector:
    app: food-order
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
